force-app/main/default/objects/Case/fields/CS_Activity__c.field-meta.xml
<CustomField>
    <fullName>CS_Activity__c</fullName>
    <description>Defines a list of CS Activities and Plays</description>
    <inlineHelpText>Defines a list of CS Activities and Plays</inlineHelpText>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CS_Reason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Anypoint Community Manager</fullName>
            </value>
            <value>
                <fullName>Anypoint Partner Manager</fullName>
            </value>
            <value>
                <fullName>API Designer API Manager</fullName>
            </value>
            <value>
                <fullName>API LC - Async</fullName>
            </value>
            <value>
                <fullName>API Lifecycle - CICD</fullName>
            </value>
            <value>
                <fullName>API Monetization</fullName>
            </value>
            <value>
                <fullName>Architecture Roadmapping</fullName>
            </value>
            <value>
                <fullName>Architecture Review</fullName>
            </value>
            <value>
                <fullName>BrownBags</fullName>
            </value>
            <value>
                <fullName>CaMA</fullName>
            </value>
            <value>
                <fullName>Citizen</fullName>
            </value>
            <value>
                <fullName>Composability Workshop</fullName>
            </value>
            <value>
                <fullName>C4E Workshop</fullName>
            </value>
            <value>
                <fullName>Dashboard and Metrics</fullName>
            </value>
            <value>
                <fullName>Deployment - Cloud</fullName>
            </value>
            <value>
                <fullName>Deployment - GovCloud</fullName>
            </value>
            <value>
                <fullName>Deployment - Hybrid</fullName>
            </value>
            <value>
                <fullName>Deployment - Onprem</fullName>
            </value>
            <value>
                <fullName>Enterprise Connectivity - Connectors</fullName>
            </value>
            <value>
                <fullName>Enterprise Connectivity - ERP</fullName>
            </value>
            <value>
                <fullName>Enterprise Connectivity - Salesforce</fullName>
            </value>
            <value>
                <fullName>Exchange</fullName>
            </value>
            <value>
                <fullName>General architectural advice</fullName>
            </value>
            <value>
                <fullName>General Design advice</fullName>
            </value>
            <value>
                <fullName>General Product advice</fullName>
            </value>
            <value>
                <fullName>Go-Live Readiness</fullName>
            </value>
            <value>
                <fullName>GraphQL(API Federation)</fullName>
            </value>
            <value>
                <fullName>Hackathon</fullName>
            </value>
            <value>
                <fullName>Health Check</fullName>
            </value>
            <value>
                <fullName>KPI Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CS_Reason__c.field-meta.xml
<CustomField>
    <fullName>CS_Reason__c</fullName>
    <description>CS reason for Tech Request</description>
    <inlineHelpText>CS reason for Tech Request</inlineHelpText>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success Planning and Advisory</fullName>
            </value>
            <value>
                <fullName>Product Specialization</fullName>
            </value>
            <value>
                <fullName>CSSA Strategic Plays</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/TRL.recordType-meta.xml
<RecordType>
    <fullName>TRL</fullName>
    <active>true</active>
    <businessProcess>CS Tech Request</businessProcess>
    <label>CS Tech Request</label>
</RecordType>

force-app/main/default/objects/Time_tracking__c/Time_tracking__c.object-meta.xml
<CustomObject>
    <label>Time tracking</label>
    <nameField>
        <label>Task</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_tracking__c/fields/Activity_Date__c.field-meta.xml
<CustomField>
    <fullName>Activity_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date when activity took place</description>
    <inlineHelpText>Date when activity took place</inlineHelpText>
    <label>Task Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_tracking__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Time tracking</relationshipLabel>
    <relationshipName>Time_tracking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_tracking__c/fields/CS_Activity__c.field-meta.xml
<CustomField>
    <fullName>CS_Activity__c</fullName>
    <description>Defines a list of CS Activities and Plays</description>
    <inlineHelpText>Defines a list of CS Activities and Plays</inlineHelpText>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CS_Reason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Anypoint Community Manager</fullName>
            </value>
            <value>
                <fullName>Anypoint Partner Manager</fullName>
            </value>
            <value>
                <fullName>API Designer API Manager</fullName>
            </value>
            <value>
                <fullName>API LC - Async</fullName>
            </value>
            <value>
                <fullName>API Lifecycle - CICD</fullName>
            </value>
            <value>
                <fullName>API Monetization</fullName>
            </value>
            <value>
                <fullName>Architecture Roadmapping</fullName>
            </value>
            <value>
                <fullName>Architecture Review</fullName>
            </value>
            <value>
                <fullName>BrownBags</fullName>
            </value>
            <value>
                <fullName>CaMA</fullName>
            </value>
            <value>
                <fullName>Citizen</fullName>
            </value>
            <value>
                <fullName>Composability Workshop</fullName>
            </value>
            <value>
                <fullName>Customer cadence/ Relationship building</fullName>
            </value>
            <value>
                <fullName>C4E Workshop</fullName>
            </value>
            <value>
                <fullName>Dashboard and Metrics</fullName>
            </value>
            <value>
                <fullName>Deployment - Cloud</fullName>
            </value>
            <value>
                <fullName>Deployment - GovCloud</fullName>
            </value>
            <value>
                <fullName>Deployment - Hybrid</fullName>
            </value>
            <value>
                <fullName>Deployment - Onprem</fullName>
            </value>
            <value>
                <fullName>Enterprise Connectivity - Connectors</fullName>
            </value>
            <value>
                <fullName>Enterprise Connectivity - ERP</fullName>
            </value>
            <value>
                <fullName>Enterprise Connectivity - Salesforce</fullName>
            </value>
            <value>
                <fullName>Exchange</fullName>
            </value>
            <value>
                <fullName>General architectural advice</fullName>
            </value>
            <value>
                <fullName>General Design advice</fullName>
            </value>
            <value>
                <fullName>General Product advice</fullName>
            </value>
            <value>
                <fullName>Go-Live Readiness</fullName>
            </value>
            <value>
                <fullName>GraphQL(API Federation)</fullName>
            </value>
            <value>
                <fullName>Hackathon</fullName>
            </value>
            <value>
                <fullName>Health Check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_tracking__c/fields/CS_Reason__c.field-meta.xml
<CustomField>
    <fullName>CS_Reason__c</fullName>
    <description>CS reason for Tech Request</description>
    <inlineHelpText>CS reason for Tech Request</inlineHelpText>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success Planning and Advisory</fullName>
            </value>
            <value>
                <fullName>Product Specialization</fullName>
            </value>
            <value>
                <fullName>CSSA Strategic Plays</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_tracking__c/fields/Delivery_Resource__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person who is delivering the task or workshop</description>
    <inlineHelpText>Person who is delivering the task or workshop</inlineHelpText>
    <label>Delivery Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Time_tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TRL_TimeTracking_ExtCtrl.cls
/*
 * App TRL Time_tracking__c custom controller
 *
 * author: A.I.
 */
public with sharing class TRL_TimeTracking_ExtCtrl {

    public Time_tracking__c newTimeTrack {get; set;}
    // Get Page URL Parameters
    public String relatedCaseId = System.currentPageReference().getParameters().get('caseid');
    String caseNumber = System.currentPageReference().getParameters().get('casenumber');
    String accountName = System.currentPageReference().getParameters().get('account_name');
    String retURL = System.currentPageReference().getParameters().get('retURL');
    String saveURL = System.currentPageReference().getParameters().get('saveURL');
    String defaultPageURL = '';
    // Handle TRL List page parameters
    public string selectedStatus = ApexPages.currentPage().getParameters().get('selectedStatus');
    public string selectedTerritory = ApexPages.currentPage().getParameters().get('selectedTerritory');
    public string selectedRegion = ApexPages.currentPage().getParameters().get('selectedRegion');
    // ----
  
    public TRL_TimeTracking_ExtCtrl() {
        init();
    }

    private void init(){
        this.newTimeTrack = new Time_tracking__c();
        this.newTimeTrack.Case__c = this.relatedCaseId;
        this.newTimeTrack.Delivery_Resource__c = UserInfo.getUserId();
        this.defaultPageURL = '/apex/TRLCase_detail_page?id='+this.relatedCaseId;
        // A.I. Comment for 2.2.0 set defaults new fields
        setDefaultFields(this.relatedCaseId);

        setSelectedParams();
        myDebug();
    }
    // Set default fields for Reason and Activity based on Case selection if they exists
    // For not existing default Success Planning and Advisory
    private void setDefaultFields(String trlCaseId){
        // Base defaults
        this.newTimeTrack.CS_Reason__c = 'Success Planning and Advisory';
        this.newTimeTrack.CS_Activity__c = 'Regular customer cadence';    
        this.newTimeTrack.Activity_Date__c = Date.Today();
        // Query Case to read Activity type values
        try{
            Case trl = [SELECT Id, CS_Reason__c, CS_Activity__c FROM Case WHERE Id =: trlCaseId];
            if(trl != null && trl.CS_Reason__c != null){
                this.newTimeTrack.CS_Reason__c = trl.CS_Reason__c;
            }
            if(trl != null && trl.CS_Activity__c != null){
                this.newTimeTrack.CS_Activity__c = trl.CS_Activity__c;    
            }    
        }catch(Exception ex){
            System.debug('No TRL Case set Reason and Activity');
        } 
    }

    private void setSelectedParams(){
        if (this.selectedStatus == null)
        	this.selectedStatus = '';
    	if (this.selectedTerritory == null)
        	this.selectedTerritory = '';
    	if (this.selectedRegion == null)
        	this.selectedRegion = '';
    }
    private void myDebug(){
        System.debug('## selectedStatus: '+selectedStatus);
        System.debug('## selectedTerritory: '+selectedTerritory);
        System.debug('## selectedRegion: '+selectedRegion);
    }

    private PageReference getPageRedirect(String url){
        PageReference pageRef = null;
        if (url != null && url.length()>0){
            pageRef = new PageReference(url);
        }
        return pageRef;
    }

    private PageReference getDefaultPageRedirect(String url){
        PageReference pageRef = getPageRedirect(url);
        if (pageRef == null){
            pageRef = new PageReference(this.defaultPageURL);                                                    
        }
        return pageRef;
    }

    public PageReference save(){
        insert newTimeTrack;
        return getDefaultPageRedirect(this.saveURL);
    }

    public PageReference cancelAction(){
        System.debug('### CANCEL Action, redirect:'+this.retURL+' OR Page: '+this.defaultPageURL);
        myDebug();
        return getDefaultPageRedirect(this.retURL);
    }

    public PageReference saveNew(){
        insert newTimeTrack;
        // Clear entry
        this.newTimeTrack = new Time_tracking__c();
        this.newTimeTrack.Case__c = this.relatedCaseId;
        this.newTimeTrack.Delivery_Resource__c = UserInfo.getUserId();

        ///this.defaultPageURL = '/apex/TRLCase_detail_page?id='+this.relatedCaseId;
        // A.I. Comment for 2.2.0 set defaults new fields
        this.newTimeTrack.CS_Reason__c = 'Success Planning and Advisory';
        this.newTimeTrack.CS_Activity__c = 'Regular customer cadence';    
        this.newTimeTrack.Activity_Date__c = Date.Today();

        return null;
    }

}