force-app/main/default/objects/Case/recordTypes/TRL.recordType-meta.xml
<RecordType>
    <fullName>TRL</fullName>
    <active>true</active>
    <businessProcess>CS Tech Request</businessProcess>
    <label>CS Tech Request</label>
</RecordType>

force-app/main/default/objects/TRL_Case_Priorization_Event__e/TRL_Case_Priorization_Event__e.object-meta.xml
<CustomObject>
    <description>#W-8097697 TRL Priorization thoeger@mulesoft.com</description>
    <label>TRL_Case_Priorization_Event</label>
    <pluralLabel>TRL_Case_Priorization_Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/TRL_Case_Priorization_Event__e/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>Case.AccountId</description>
    <label>AccountId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TRL_Case_Priorization_Event__e/fields/CaseID__c.field-meta.xml
<CustomField>
    <fullName>CaseID__c</fullName>
    <label>CaseID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TRL_Submit_CasePlatformEventTest.cls
/***
*  @name: TRL_Submit_CasePlatformEvent to externalize method for submission of the PE
*  @GUS: #W-8097697
*  @Author: thoeger@mulesoft.com
*  @CreationDate: 2020-October-21
* 
* */
@IsTest
public class TRL_Submit_CasePlatformEventTest {
    Final static string DebugClass = '## TRL_Submit_CasePlatformEventTest ';


    @testSetUp
    static void setUpData(){
        Account a = new Account();
        a.name = 'Test Account';
        // a.ADR_Owner_User_Sales_Theater__c = 'EMEA';
        // a.AnnualRevenue = 4000000000;
        a.BillingCountry = 'Germany';
        insert a;
        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');
        Case testCase = new Case();
        testCase.RecordTypeId = trlRecordType.getRecordTypeId();
        testCase.Subject = 'TRL Case subject';
        testCase.AccountId = a.Id;
        insert testCase;
    }
    

    
    @IsTest 
    static void testTRL_CasePE_Publish(){
        Final String DebugMethod = DebugClass + ' testTRL_CasePE_Publish ';
        system.debug(DebugMethod + 'I am here now!');
        Case testCase = [SELECT Id, AccountID FROM Case WHERE Subject = 'TRL Case subject' LIMIT 1];

        Test.startTest();

        TRL_Submit_CasePlatformEvent t = new TRL_Submit_CasePlatformEvent();
        t.Submit_TRL_CasePlatformEvent(testCase);
        system.debug(DebugMethod + ' Event submitted:' + t);

        /** 
        TRL_Case_Priorization_Event__e newEvent = new TRL_Case_Priorization_Event__e(
            AccountId__c=testCase.AccountID,
            CaseID__c=testCase.id
        );
        Database.SaveResult sr = EventBus.publish(newEvent);  
         // Verify that the publish was successful
         System.assertEquals(true, sr.isSuccess());
        
         // Deliver the test event before Test.stopTest()
         Test.getEventBus().deliver();     
         Test.stopTest();   
         **/
    }
    
}