force-app/main/default/objects/Account/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <description>Calculates an Account&apos;s Annual Recurring Revenue</description>
    <label>ARR</label>
    <summarizedField>Opportunity.Product_Annual_Sum__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.Type</field>
        <operation>equals</operation>
        <value>Renewal</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>notEqual</operation>
        <value>Sales Qualified Lead PW, Sales Qualified Lead - Stale, Proposal Out, Negotiation, Sales Qualified Lead, Closed Won, Closed Lost, Rejected Lead</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/CS_Tech_Priority__c.field-meta.xml
<CustomField>
    <fullName>CS_Tech_Priority__c</fullName>
    <label>CS Tech Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CSSA_Renewal_Quota__c.field-meta.xml
<CustomField>
    <fullName>CSSA_Renewal_Quota__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Location: will be used for reporting only – should not be on a page layout for any function – we just need to be able to report on this field
Business justification: For compensation, we need a reliable way to track which accounts will be included in the CSSA renewal quota.


Case #08239234</description>
    <label>CSSA Renewal Quota</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Focus_Account_Level__c.field-meta.xml
<CustomField>
    <fullName>Focus_Account_Level__c</fullName>
    <label>Focus Account Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Theater</fullName>
            </value>
            <value>
                <fullName>Area</fullName>
            </value>
            <value>
                <fullName>Sales Team</fullName>
            </value>
            <value>
                <fullName>Sales Sub Team</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Next_Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Renewal_Date__c</fullName>
    <description>shows the next renewal close date</description>
    <label>Next Renewal Date</label>
    <summarizedField>Opportunity.CloseDate</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.Type</field>
        <operation>equals</operation>
        <value>Renewal</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.IsClosed</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region</description>
    <label>OU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Territory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>ROA</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FINS</fullName>
            </value>
            <value>
                <fullName>HLS</fullName>
            </value>
            <value>
                <fullName>RCG</fullName>
            </value>
            <value>
                <fullName>CMT</fullName>
            </value>
            <value>
                <fullName>EBU</fullName>
            </value>
            <value>
                <fullName>CBU</fullName>
            </value>
            <value>
                <fullName>PubSec</fullName>
            </value>
            <value>
                <fullName>DACH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Theater</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMER</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Top_1000_Joint_Account__c.field-meta.xml
<CustomField>
    <fullName>Top_1000_Joint_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Focus Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Weighted_Open_ACV__c.field-meta.xml
<CustomField>
    <fullName>Weighted_Open_ACV__c</fullName>
    <label>Weighted Open ACV</label>
    <summarizedField>Opportunity.Weighted_ACV_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.Type</field>
        <operation>equals</operation>
        <value>New Business, Add-On Business, Add-On Business - Renewal Price Uplift</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>1. ID Business Initiative, 2. Educate on MuleSoft Vision, 3. Confirm Need &amp; Impact, 4. Validate Solution, 5. Negotiate &amp; Close, 6. Submitted for Closing, 7. Booking</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>DACH</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>SEEMA</fullName>
            </value>
            <value>
                <fullName>ASEAN</fullName>
            </value>
            <value>
                <fullName>NORTH APAC</fullName>
            </value>
            <value>
                <fullName>KOR</fullName>
            </value>
            <value>
                <fullName>INDIAN SUB</fullName>
            </value>
            <value>
                <fullName>JP</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/TRL_Calc_Prio_Score__c.field-meta.xml
<CustomField>
    <fullName>TRL_Calc_Prio_Score__c</fullName>
    <description>CS TRL Calculated Priority populated from Priorization calculation, #W-8097697</description>
    <inlineHelpText>Prioritization Score (0-10 : Low-High)</inlineHelpText>
    <label>CS TRL Calculated Priority Score</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/TRL_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>TRL_Request_Type__c</fullName>
    <description>CS Request Type for Priorization, #W-8097697</description>
    <inlineHelpText>CS Request Type for Priorization</inlineHelpText>
    <label>CS Priorization Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>strategic</fullName>
                <label>Strategic</label>
            </value>
            <value>
                <fullName>tactical</fullName>
                <label>Tactical</label>
            </value>
            <value>
                <fullName>unspecified</fullName>
                <default>true</default>
                <label>unspecified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/TRL_Task_Is_Clear__c.field-meta.xml
<CustomField>
    <fullName>TRL_Task_Is_Clear__c</fullName>
    <description>CS Task Clarity Status after review, for Priorization, #W-8097697</description>
    <inlineHelpText>CS Task Clarity Status after review, for Priorization</inlineHelpText>
    <label>CS Task Clarity Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>yes</fullName>
            </value>
            <value>
                <fullName>no</fullName>
            </value>
            <value>
                <fullName>unspecified</fullName>
                <default>true</default>
                <label>unspecified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/TRL.recordType-meta.xml
<RecordType>
    <fullName>TRL</fullName>
    <active>true</active>
    <businessProcess>CS Tech Request</businessProcess>
    <label>CS Tech Request</label>
</RecordType>

force-app/main/default/objects/TRL_Priorization_Config__c/TRL_Priorization_Config__c.object-meta.xml
<CustomObject>
    <label>CS Tech Request Priorization Config</label>
    <nameField>
        <displayFormat>ID{0000}</displayFormat>
        <label>CS Tech Request Priorization Config</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CS Tech Request Priorization Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TRL_Priorization_Config__c/fields/FieldLabel__c.field-meta.xml
<CustomField>
    <fullName>FieldLabel__c</fullName>
    <label>FieldLabel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TRL_Prio_Fields</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TRL_Priorization_Config__c/fields/Filter_Score__c.field-meta.xml
<CustomField>
    <fullName>Filter_Score__c</fullName>
    <label>Filter Score Percentage (Col H)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TRL_Priorization_Config__c/fields/FilterType__c.field-meta.xml
<CustomField>
    <fullName>FilterType__c</fullName>
    <inlineHelpText>only for parent records</inlineHelpText>
    <label>FilterType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Range</fullName>
            </value>
            <value>
                <fullName>Value</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TRL_Priorization_Config__c/fields/IsParent__c.field-meta.xml
<CustomField>
    <fullName>IsParent__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>if true: defines the Weighted score</inlineHelpText>
    <label>IsParent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TRL_Priorization_Config__c/fields/Parent_Filter__c.field-meta.xml
<CustomField>
    <fullName>Parent_Filter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Filter</label>
    <referenceTo>TRL_Priorization_Config__c</referenceTo>
    <relationshipLabel>Configuration Values</relationshipLabel>
    <relationshipName>Config</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TRL_Priorization_Config__c/fields/Score_Weight__c.field-meta.xml
<CustomField>
    <fullName>Score_Weight__c</fullName>
    <inlineHelpText>% Weight for the Score - col E</inlineHelpText>
    <label>% Weight</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TRL_Priorization_Config__c/fields/Scoring_Factor__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Factor__c</fullName>
    <inlineHelpText>Weighted Score - col F</inlineHelpText>
    <label>Weighted Score</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TRL_Priorization_Config__c/fields/ScoringString__c.field-meta.xml
<CustomField>
    <fullName>ScoringString__c</fullName>
    <label>ScoringString</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TRL_Priorization_Config__c/fields/Theather__c.field-meta.xml
<CustomField>
    <fullName>Theather__c</fullName>
    <label>Theather</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>AMER</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TRL_Prio_Fields.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>account.ARR__c</fullName>
        <label>AOV</label>
    </customValue>
    <customValue>
        <fullName>case.TRL_Task_Is_Clear__c</fullName>
        <label>Business Justification Provided</label>
    </customValue>
    <customValue>
        <fullName>account.Focus_Account_Level__c</fullName>
        <label>Focus Account</label>
    </customValue>
    <customValue>
        <fullName>case.CS_Tech_Priority__c</fullName>
        <label>CS Priority</label>
    </customValue>
    <customValue>
        <fullName>account.Weighted_Open_ACV__c</fullName>
        <label>Open ACV</label>
    </customValue>
    <customValue>
        <fullName>account.CSSA_Renewal_Quota__c</fullName>
        <label>Renewal Base</label>
    </customValue>
    <masterLabel>TRL_Prio_Fields</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/TRL_Case_Priorization_CalculationTest.cls
@IsTest
public class TRL_Case_Priorization_CalculationTest {
    Final static string DebugClass = '## TRL_Case_Priorization_CalculationTest ';


    @testSetUp
    static void setUpData()
    {
        Final String DebugMethod = DebugClass + ' setUpData ';
        system.debug(DebugMethod + 'I am here now!');

        // Set config record for EMEA
        TRL_Priorization_Config__c pc = new TRL_Priorization_Config__c();
        // Parent
        pc.IsParent__c = true;
        pc.FieldLabel__c = 'case.CS_Tech_Priority__c';
        pc.FilterType__c = 'Range';
        pc.Score_Weight__c = 5;
        pc.Scoring_Factor__c = 0.4;
        pc.Theather__c = 'EMEA';
        insert pc;

        List<TRL_Priorization_Config__c> lst = new List<TRL_Priorization_Config__c>();

        TRL_Priorization_Config__c ch1 = new TRL_Priorization_Config__c();
        ch1.IsParent__c = false;
        ch1.Parent_Filter__c = pc.Id;
        ch1.Filter_Score__c = 30;
        ch1.ScoringString__c = 'Low';
        lst.add(ch1);

        TRL_Priorization_Config__c ch2 = new TRL_Priorization_Config__c();
        ch2.IsParent__c = false;
        ch2.Parent_Filter__c = pc.Id;
        ch2.Filter_Score__c = 100;
        ch2.ScoringString__c = 'High';
        lst.add(ch2);

        TRL_Priorization_Config__c ch3 = new TRL_Priorization_Config__c();
        ch3.IsParent__c = false;
        ch3.Parent_Filter__c = pc.Id;
        ch3.Filter_Score__c = 60;
        ch3.ScoringString__c = 'Medium';
        lst.add(ch3);
        insert lst;

        Account a = new Account();
        a.name = 'Test Account';
        // a.ADR_Owner_User_Sales_Theater__c = 'EMEA';
        // a.AnnualRevenue = 4000000000;
        a.BillingCountry = 'Germany';
        a.Territory__c = 'EMEA'; 
        a.Region__c = 'NE';
        a.CS_Tech_Priority__c = 'High';
        a.Focus_Account_Level__c = 'Theater';
        a.CSSA_Renewal_Quota__c = true;
        insert a;
        system.debug(DebugMethod + 'inderting account:'+a);
        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');
        Case testCase = new Case();
        testCase.RecordTypeId = trlRecordType.getRecordTypeId();
        testCase.Subject = 'TRL Case subject';
        testCase.AccountId = a.Id;
        testCase.TRL_Task_Is_Clear__c = 'yes';
        insert testCase;
        system.debug(DebugMethod + 'inderting testCase:'+testCase);

    }

    @IsTest //(SeeAllData=true) // to verify that config data in in does not work with testsetup
    static void testTRL_Case_Priorization_Calculation(){
        Final String DebugMethod = DebugClass + ' testTRL_Case_Priorization_Calculation ';
        system.debug(DebugMethod + 'I am here now!');

        String caseQueryString = 'select ' 
        + ' id '
        + ', TRL_Task_Is_Clear__c '
       // + ', TRL_Request_Type__c '
        + ', TRL_Calc_Prio_Score__c '
        + ', CaseNumber '
        + ', accountId '
        + ', account.ARR__c '
        + ', account.CSSA_Renewal_Quota__c '
        + ', account.Next_Renewal_Date__c '
        + ', account.Weighted_Open_ACV__c '
        + ', account.Top_1000_Joint_Account__c '
        + ', account.Focus_Account_Level__c '
        + ', account.CS_Tech_Priority__c  '
        + ', account.Territory__c '
        + ' from case ';
        String caseQueryStringFull = caseQueryString + ' where Subject= \'TRL Case subject\'';
        system.debug(DebugMethod + 'using caseQueryStringFull:'+ caseQueryStringFull);
        //Case testCase = [SELECT Id, AccountID FROM Case WHERE Subject = 'TRL Case subject' LIMIT 1];
        Case testCase = database.query(caseQueryStringFull);
        system.debug(DebugMethod + 'using case:'+ testCase);

        TRL_Case_Priorization_Calculation TRLCPCalc= new TRL_Case_Priorization_Calculation();

        Test.startTest();
        TRLCPCalc.calculatePrio(testCase.id);  
        Test.stopTest();
    
    }
    
}