force-app/main/default/objects/Account/fields/CS_Area__c.field-meta.xml
<CustomField>
    <fullName>CS_Area__c</fullName>
    <label>CS Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Territory__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>CBU</fullName>
            </value>
            <value>
                <fullName>CMT</fullName>
            </value>
            <value>
                <fullName>DACH</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>EBU</fullName>
            </value>
            <value>
                <fullName>FINS</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>HLS</fullName>
            </value>
            <value>
                <fullName>Indian Sub</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>PubSec</fullName>
            </value>
            <value>
                <fullName>RCG</fullName>
            </value>
            <value>
                <fullName>ROA</fullName>
            </value>
            <value>
                <fullName>ROE</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region</description>
    <label>OU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Territory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>ROA</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FINS</fullName>
            </value>
            <value>
                <fullName>HLS</fullName>
            </value>
            <value>
                <fullName>RCG</fullName>
            </value>
            <value>
                <fullName>CMT</fullName>
            </value>
            <value>
                <fullName>EBU</fullName>
            </value>
            <value>
                <fullName>CBU</fullName>
            </value>
            <value>
                <fullName>PubSec</fullName>
            </value>
            <value>
                <fullName>DACH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Theater</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMER</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CS_Activity__c.field-meta.xml
<CustomField>
    <fullName>CS_Activity__c</fullName>
    <description>Defines a list of CS Activities and Plays</description>
    <inlineHelpText>Defines a list of CS Activities and Plays</inlineHelpText>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CS_Reason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Anypoint Community Manager</fullName>
            </value>
            <value>
                <fullName>Anypoint Partner Manager</fullName>
            </value>
            <value>
                <fullName>API Designer API Manager</fullName>
            </value>
            <value>
                <fullName>API LC - Async</fullName>
            </value>
            <value>
                <fullName>API Lifecycle - CICD</fullName>
            </value>
            <value>
                <fullName>API Monetization</fullName>
            </value>
            <value>
                <fullName>Architecture Roadmapping</fullName>
            </value>
            <value>
                <fullName>Architecture Review</fullName>
            </value>
            <value>
                <fullName>BrownBags</fullName>
            </value>
            <value>
                <fullName>CaMA</fullName>
            </value>
            <value>
                <fullName>Citizen</fullName>
            </value>
            <value>
                <fullName>Composability Workshop</fullName>
            </value>
            <value>
                <fullName>C4E Workshop</fullName>
            </value>
            <value>
                <fullName>Dashboard and Metrics</fullName>
            </value>
            <value>
                <fullName>Deployment - Cloud</fullName>
            </value>
            <value>
                <fullName>Deployment - GovCloud</fullName>
            </value>
            <value>
                <fullName>Deployment - Hybrid</fullName>
            </value>
            <value>
                <fullName>Deployment - Onprem</fullName>
            </value>
            <value>
                <fullName>Enterprise Connectivity - Connectors</fullName>
            </value>
            <value>
                <fullName>Enterprise Connectivity - ERP</fullName>
            </value>
            <value>
                <fullName>Enterprise Connectivity - Salesforce</fullName>
            </value>
            <value>
                <fullName>Exchange</fullName>
            </value>
            <value>
                <fullName>General architectural advice</fullName>
            </value>
            <value>
                <fullName>General Design advice</fullName>
            </value>
            <value>
                <fullName>General Product advice</fullName>
            </value>
            <value>
                <fullName>Go-Live Readiness</fullName>
            </value>
            <value>
                <fullName>GraphQL(API Federation)</fullName>
            </value>
            <value>
                <fullName>Hackathon</fullName>
            </value>
            <value>
                <fullName>Health Check</fullName>
            </value>
            <value>
                <fullName>KPI Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CS_Reason__c.field-meta.xml
<CustomField>
    <fullName>CS_Reason__c</fullName>
    <description>CS reason for Tech Request</description>
    <inlineHelpText>CS reason for Tech Request</inlineHelpText>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success Planning and Advisory</fullName>
            </value>
            <value>
                <fullName>Product Specialization</fullName>
            </value>
            <value>
                <fullName>CSSA Strategic Plays</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>DACH</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>SEEMA</fullName>
            </value>
            <value>
                <fullName>ASEAN</fullName>
            </value>
            <value>
                <fullName>NORTH APAC</fullName>
            </value>
            <value>
                <fullName>KOR</fullName>
            </value>
            <value>
                <fullName>INDIAN SUB</fullName>
            </value>
            <value>
                <fullName>JP</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/TRL.recordType-meta.xml
<RecordType>
    <fullName>TRL</fullName>
    <active>true</active>
    <businessProcess>CS Tech Request</businessProcess>
    <label>CS Tech Request</label>
</RecordType>

force-app/main/default/objects/Time_tracking__c/Time_tracking__c.object-meta.xml
<CustomObject>
    <label>Time tracking</label>
    <nameField>
        <label>Task</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_tracking__c/fields/CS_Reason__c.field-meta.xml
<CustomField>
    <fullName>CS_Reason__c</fullName>
    <description>CS reason for Tech Request</description>
    <inlineHelpText>CS reason for Tech Request</inlineHelpText>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success Planning and Advisory</fullName>
            </value>
            <value>
                <fullName>Product Specialization</fullName>
            </value>
            <value>
                <fullName>CSSA Strategic Plays</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TRL_TimeTracking_ExtCtrlTest.cls
/*
 * App TRL Time_tracking__c controller  unit test class
 *
 * author: A.I.
 */
@IsTest
private class TRL_TimeTracking_ExtCtrlTest {
    
    @testSetUp
    static void setUpData(){
        Account acct = new Account();
        acct.Name = 'TRL Test Account';
        acct.Territory__c = 'AMER';
        acct.CS_Area__c = 'West';
        acct.Region__c = 'West';

        // Fill some required fields for CSDEV or NA101
        acct.Industry = 'Insurance';
        acct.AnnualRevenue = 12000000;
        acct.CurrencyIsoCode = 'USD';
        acct.BillingCountry = 'USA';
        insert acct;

        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');
        Case testCase = new Case();
        testCase.RecordTypeId = trlRecordType.getRecordTypeId();
        testCase.AccountId = acct.Id;
        testCase.Subject = 'TRL case';
        testCase.Status = 'New';
        testCase.CS_Reason__c = 'Success Planning and Advisory';
        testCase.CS_Activity__c ='General architectural advice';
        insert testCase;

    }

    @IsTest
    static void testTRL_TimeTracking_ExtCtrl(){
    
        TRL_TimeTracking_ExtCtrl ctrl = new TRL_TimeTracking_ExtCtrl();
    
        Test.startTest();

        Test.stopTest();
    }

    @IsTest
    static void testSave(){
        Case testCase = [SELECT Id, Subject, Description FROM Case LIMIT 1];

        TRL_TimeTracking_ExtCtrl ctrl = new TRL_TimeTracking_ExtCtrl();
        ctrl.newTimeTrack.Case__c = testCase.Id;
        ctrl.newTimeTrack.Name = 'Test Task 1';
        ctrl.newTimeTrack.Time_spent__c = 1;
        ctrl.newTimeTrack.Description__c = 'Test desc text';

        // --- New fields for 2.2.0  
        ctrl.newTimeTrack.Activity_Date__c = Date.today();
        ctrl.newTimeTrack.CS_Reason__c = 'Success Planning and Advisory';
        ctrl.newTimeTrack.CS_Activity__c ='General architectural advice';

        Test.startTest();
        ctrl.save();
        Test.stopTest();

        List<Time_tracking__c> timeLog = [SELECT Id, Name FROM Time_tracking__c];
        Boolean res = false;
        if(timeLog.size() > 0){res=true;}
        System.assertEquals(true, res);
    }

    @IsTest
    static void testSaveNew(){
        Case testCase = [SELECT Id, Subject, Description FROM Case LIMIT 1];

        TRL_TimeTracking_ExtCtrl ctrl = new TRL_TimeTracking_ExtCtrl();
        ctrl.newTimeTrack.Case__c = testCase.Id;
        ctrl.newTimeTrack.Name = 'Test Task 1';
        ctrl.newTimeTrack.Time_spent__c = 1;
        ctrl.newTimeTrack.Description__c = 'Test desc text';
        // --- New fields for 2.2.0  
        ctrl.newTimeTrack.Activity_Date__c = Date.today();
        ctrl.newTimeTrack.CS_Reason__c = 'Success Planning and Advisory';
        ctrl.newTimeTrack.CS_Activity__c ='General architectural advice';

        Test.startTest();
        ctrl.saveNew();
        Test.stopTest();

        Time_tracking__c tlog = [SELECT Id, Name, Description__c FROM Time_tracking__c LIMIT 1];
        System.assertEquals('Test Task 1', tlog.Name);
        System.assertEquals('Test desc text', tlog.Description__c);

    }

    @IsTest
    static void testcancelAction(){
        TRL_TimeTracking_ExtCtrl ctrl = new TRL_TimeTracking_ExtCtrl();

        Test.startTest();
        PageReference testRef = ctrl.cancelAction(); 
        Test.stopTest();

        // Asserts test
        System.assertNotEquals(null, testRef);
        //System.assert(testRef.getRedirect());
    }

}