force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region</description>
    <label>OU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Territory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>ROA</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FINS</fullName>
            </value>
            <value>
                <fullName>HLS</fullName>
            </value>
            <value>
                <fullName>RCG</fullName>
            </value>
            <value>
                <fullName>CMT</fullName>
            </value>
            <value>
                <fullName>EBU</fullName>
            </value>
            <value>
                <fullName>CBU</fullName>
            </value>
            <value>
                <fullName>PubSec</fullName>
            </value>
            <value>
                <fullName>DACH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Theater</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMER</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Account_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Region__c</fullName>
    <formula>TEXT(Account.Territory__c) + &quot; - &quot; + TEXT(Account.Region__c)</formula>
    <label>Account Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>DACH</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>SEEMA</fullName>
            </value>
            <value>
                <fullName>ASEAN</fullName>
            </value>
            <value>
                <fullName>NORTH APAC</fullName>
            </value>
            <value>
                <fullName>KOR</fullName>
            </value>
            <value>
                <fullName>INDIAN SUB</fullName>
            </value>
            <value>
                <fullName>JP</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/TRL.recordType-meta.xml
<RecordType>
    <fullName>TRL</fullName>
    <active>true</active>
    <businessProcess>CS Tech Request</businessProcess>
    <label>CS Tech Request</label>
</RecordType>

force-app/main/default/classes/TRL_Cases_onlyTest.cls
@IsTest
public class TRL_Cases_onlyTest {
    
    @TestSetUp 
    static void testSetUp(){
        List<Case> testCases = new List<Case>(); 
        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');

        Boolean statusIndicator = false;

        Account account1 = new Account(Name = 'TestAccount1', Territory__c = 'AMER', Region__c = 'North', BillingCountry = 'US');
        insert account1;

        for(Integer i = 0; i < 55; i++){
            Case c = new Case(RecordTypeId = trlRecordType.getRecordTypeId(),
                    Subject = 'Test ' + i,
                    Status = statusIndicator ? 'Work in Progress' : 'New',
                    AccountId = account1.Id);
            testCases.add(c);
            statusIndicator = !statusIndicator;
        }

        Account account2 = new Account(Name = 'AcoountApex', Territory__c = 'EMEA', Region__c = 'NE', BillingCountry = 'France');
        insert account2;

        for(Integer i = 0; i < 55; i++){
            Case c = new Case(RecordTypeId = trlRecordType.getRecordTypeId(),
                    Subject = 'Test ' + i,
                    Status = statusIndicator ? 'Work in Progress' : 'New',
                    AccountId = account2.Id);
            testCases.add(c);
            statusIndicator = !statusIndicator;
        }
        
        testCases.add(new Case(Subject = 'NonTRL Case'));
        testCases.add(new Case(Subject = 'NonTRL Case 2'));
        
        insert testCases;
    }
    
    @IsTest 
    static void testTRL_Cases_Only(){
        
        Test.startTest();
        
        TRL_Cases_Only ctrl = new TRL_Cases_Only();  
        ctrl.user_role = true;      

        Test.stopTest();
        
        System.assertEquals(1, ctrl.currentPage);
        System.assertEquals(50, ctrl.listSize);
        System.assertEquals(110, ctrl.totalSize);
        
        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');
        
        for(Case c : [SELECT RecordTypeId FROM Case WHERE Id IN : ctrl.cases]){
            System.assertEquals(trlRecordType.getRecordTypeId(), c.RecordTypeId);
        }
        
        System.assert(ctrl.cases.size() <= ctrl.listSize);
        
    }

    @IsTest 
    static void testRefreshCasesView(){
        
        Test.startTest();
        
        TRL_Cases_Only ctrl = new TRL_Cases_Only();  
        ctrl.refreshCaseView();    

        Test.stopTest();
        
        System.assertEquals(1, ctrl.currentPage);
        System.assertEquals(50, ctrl.listSize);
        System.assertEquals(110, ctrl.totalSize);
        
        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');
        
        for(Case c : [SELECT RecordTypeId FROM Case WHERE Id IN : ctrl.cases]){
            System.assertEquals(trlRecordType.getRecordTypeId(), c.RecordTypeId);
        }
        
        System.assert(ctrl.cases.size() <= ctrl.listSize);
        
    }

    @IsTest 
    static void testSearchCasesPositive(){
        
        Test.startTest();
        
        TRL_Cases_Only ctrl = new TRL_Cases_Only();        
        ctrl.searchExpression = 'TestAccount1';
        ctrl.reloadCases();

        Test.stopTest();
        
        System.assertEquals(1, ctrl.currentPage);
        System.assertEquals(50, ctrl.listSize);
        System.assertEquals(110, ctrl.totalSize); // All cases with Account name TestAccount1
        
    }

    @IsTest 
    static void testGetSortDirection(){
        
        Test.startTest();
        
        TRL_Cases_Only ctrl = new TRL_Cases_Only();        
        String sortDirection = ctrl.getSortDirection();

        Test.stopTest();
        
        System.assertEquals('ASC', sortDirection);
    }
    @IsTest 
    static void testSetSortDirection(){
        
        Test.startTest();
        
        TRL_Cases_Only ctrl = new TRL_Cases_Only();
        ctrl.sortExpression = 'DESC';
        ctrl.setSortDirection('DESC' );      
        String sortDirection = ctrl.getSortDirection();

        Test.stopTest();
        
        System.assertEquals('DESC', sortDirection);
        System.assertEquals('DESC', ctrl.sortExpression);
    }

    @isTest
    static void testStatusItems(){
        TRL_Cases_only ctrl = new TRL_Cases_only();
        
        Test.startTest();
        
        List<SelectOption> opt = ctrl.getStatusItems();
        Test.stopTest();
        System.assertNotEquals(0, opt.size());
        System.assertEquals('--None--', opt[0].getValue());

    }

    @isTest
    static void testTheaterItems(){
        TRL_Cases_only ctrl = new TRL_Cases_only();
        
        Test.startTest();
        List<SelectOption> opt = ctrl.getTheaterItems();
        Test.stopTest();
        System.assertNotEquals(0, opt.size());
        System.assertEquals('--None--', opt[0].getValue());

    }

    @isTest
    static void testRegionItems(){
        TRL_Cases_only ctrl = new TRL_Cases_only();
        
        Test.startTest();
        
        List<SelectOption> opt = ctrl.getRegionItems();
        Test.stopTest();
        System.assertNotEquals(0, opt.size());
        System.assertEquals('--None--', opt[0].getValue());
    }
    @isTest
    static void testAreaDisaplay(){
        TRL_Cases_only ctrl = new TRL_Cases_only();
        
        Test.startTest();
        
        Boolean sel = ctrl.getAreaDisaplay();

        Test.stopTest();
        System.assertEquals(true, sel);

    }
    @isTest
    static void testAreaDisaplaySetNull(){
        TRL_Cases_only ctrl = new TRL_Cases_only();
        ctrl.selectedTheater = null;
        Test.startTest();
        
        Boolean sel = ctrl.getAreaDisaplay();

        Test.stopTest();
        System.assertEquals(true, sel);

    }

    @isTest
    static void testgoToSortColumn(){
        TRL_Cases_only ctrl = new TRL_Cases_only();
        
        Test.startTest();
        
        ctrl.goToSortColumn();

        Test.stopTest();
        //System.assertEquals(true, sel);

    }

    


    @IsTest
    static void testNewCase(){
        TRL_Cases_only ctrl = new TRL_Cases_only();
        
        Test.startTest();
        
        PageReference testRef = ctrl.newCase();        
        
        Test.stopTest();
        
        System.assertNotEquals(null, testRef);
        System.assert(testRef.getRedirect());
        
    }
    
    @IsTest
    static void testGoToFirstPage(){
        
        TRL_Cases_only ctrl = new TRL_Cases_only();
        ctrl.goToNextPage();
        System.assertNotEquals(1, ctrl.currentPage);
        
        Test.startTest();
        
        ctrl.goToFirstPage();        
        
        Test.stopTest();
        
        System.assertEquals(1, ctrl.currentPage);
        
        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');
        
        for(Case c : [SELECT RecordTypeId FROM Case WHERE Id IN : ctrl.cases]){
            System.assertEquals(trlRecordType.getRecordTypeId(), c.RecordTypeId);
        }
        
        System.assert(ctrl.cases.size() <= ctrl.listSize);
        
    }
    
    @IsTest
    static void testGoToPreviousPage(){
        
        TRL_Cases_only ctrl = new TRL_Cases_only();
        ctrl.goToNextPage();
        ctrl.goToNextPage();
        System.assertEquals(3, ctrl.currentPage);
        
        Test.startTest();
        
        ctrl.goToPreviousPage();        
        
        Test.stopTest();
        
        System.assertEquals(2, ctrl.currentPage);
        
        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');
        
        for(Case c : [SELECT RecordTypeId FROM Case WHERE Id IN : ctrl.cases]){
            System.assertEquals(trlRecordType.getRecordTypeId(), c.RecordTypeId);
        }
        
        System.assert(ctrl.cases.size() <= ctrl.listSize);
    }
    
    @IsTest
    static void testGoToNextPage(){
        
        TRL_Cases_only ctrl = new TRL_Cases_only();
        
        Test.startTest();
        
        ctrl.goToNextPage();        
        
        Test.stopTest();
        
        System.assertEquals(2, ctrl.currentPage);
        
        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');
        
        for(Case c : [SELECT RecordTypeId FROM Case WHERE Id IN : ctrl.cases]){
            System.assertEquals(trlRecordType.getRecordTypeId(), c.RecordTypeId);
        }
        
        System.assert(ctrl.cases.size() <= ctrl.listSize);
    }
    
    @IsTest
    static void testGoToEndPage(){
        
        TRL_Cases_only ctrl = new TRL_Cases_only();
        
        Test.startTest();
        
        ctrl.goToEndPage();        
        
        Test.stopTest();
        
        System.assertEquals(3, ctrl.currentPage);
        
        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');
        
        for(Case c : [SELECT RecordTypeId FROM Case WHERE Id IN : ctrl.cases]){
            System.assertEquals(trlRecordType.getRecordTypeId(), c.RecordTypeId);
        }
        
        System.assert(ctrl.cases.size() <= ctrl.listSize);
    }

    @IsTest
    static void testReloadCases() {
        TRL_Cases_Only ctrl = new TRL_Cases_Only();

        Test.startTest();

        ctrl.reloadCases();

        Test.stopTest();

        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');

        for(Case c : [SELECT RecordTypeId FROM Case WHERE Id IN : ctrl.cases]){
            System.assertEquals(trlRecordType.getRecordTypeId(), c.RecordTypeId);
        }

        System.assert(ctrl.cases.size() <= ctrl.listSize);
                
        System.assertEquals(1, ctrl.currentPage);
        System.assertEquals(110, ctrl.totalSize);
    }

    @IsTest
    static void testReloadCasesWithStatus() {
        TRL_Cases_Only ctrl = new TRL_Cases_Only();
        ctrl.caseForStatus.Status = 'New';
        ctrl.selectedCaseStatus = 'New';
        Test.startTest();

        ctrl.reloadCases();

        Test.stopTest();

        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');

        for(Case c: ctrl.cases) {
            System.assertEquals('New', c.Status);
        }

        for(Case c : [SELECT RecordTypeId FROM Case WHERE Id IN : ctrl.cases]){
            System.assertEquals(trlRecordType.getRecordTypeId(), c.RecordTypeId);
        }

        System.assert(ctrl.cases.size() <= ctrl.listSize);
        
        System.assertEquals(1, ctrl.currentPage);
        System.assertEquals(55, ctrl.totalSize);
    }

    @IsTest
    static void testReloadCasesWithTerritory() {
        TRL_Cases_Only ctrl = new TRL_Cases_Only();
        ctrl.accountForTerritory.Territory__c = 'AMER';
        ctrl.selectedTheater = 'AMER';

        Test.startTest();

        ctrl.reloadCases();

        Test.stopTest();

        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');

        for(Case c: ctrl.cases) {
            System.assert(c.Account_Region__c.contains('AMER'));
        }

        for(Case c : [SELECT RecordTypeId FROM Case WHERE Id IN : ctrl.cases]){
            System.assertEquals(trlRecordType.getRecordTypeId(), c.RecordTypeId);
        }

        System.assert(ctrl.cases.size() <= ctrl.listSize);
        
        System.assertEquals(1, ctrl.currentPage);
        System.assertEquals(55, ctrl.totalSize);
    }

    @IsTest
    static void testReloadCasesWithRegion() {
        TRL_Cases_Only ctrl = new TRL_Cases_Only();
        ctrl.accountForTerritory.Territory__c = 'AMER';
        ctrl.accountForTerritory.Region__c = 'North';
        ctrl.selectedTheater = 'AMER';
        ctrl.selectedArea = 'North';
        Test.startTest();

        ctrl.reloadCases();

        Test.stopTest();

        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');

        for(Case c: ctrl.cases) {
            System.assert(c.Account_Region__c.contains('North'));
        }

        for(Case c : [SELECT RecordTypeId FROM Case WHERE Id IN : ctrl.cases]){
            System.assertEquals(trlRecordType.getRecordTypeId(), c.RecordTypeId);
        }

        System.assert(ctrl.cases.size() <= ctrl.listSize);
        
        System.assertEquals(1, ctrl.currentPage);
        System.assertEquals(55, ctrl.totalSize);
    }

    @IsTest
    static void testReloadCasesWithTerritoryAndStatus() {
        TRL_Cases_Only ctrl = new TRL_Cases_Only();
        ctrl.caseForStatus.Status = 'New';
        ctrl.accountForTerritory.Territory__c = 'AMER';
        ctrl.selectedCaseStatus = 'New';
        ctrl.selectedTheater = 'AMER';

        Test.startTest();

        ctrl.reloadCases();

        Test.stopTest();

        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');

        for(Case c: ctrl.cases) {
            System.assert(c.Account_Region__c.contains('AMER'));
            System.assertEquals('New', c.Status);
        }

        for(Case c : [SELECT RecordTypeId FROM Case WHERE Id IN : ctrl.cases]){
            System.assertEquals(trlRecordType.getRecordTypeId(), c.RecordTypeId);
        }

        System.assert(ctrl.cases.size() <= ctrl.listSize);
        
        System.assertEquals(1, ctrl.currentPage);
        System.assertEquals(28, ctrl.totalSize);
    }

    @IsTest
    static void testReloadCasesError() {
        TRL_Cases_Only ctrl = new TRL_Cases_Only();
        ctrl.caseForStatus.Status = 'Ne\'w';
        ctrl.selectedCaseStatus = 'Ne\'w';
        Test.startTest();

        ctrl.reloadCases();

        Test.stopTest();

        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');

        for(Case c: ctrl.cases) {
            System.assertEquals('New', c.Status);
        }

        for(Case c : [SELECT RecordTypeId FROM Case WHERE Id IN : ctrl.cases]){
            System.assertEquals(trlRecordType.getRecordTypeId(), c.RecordTypeId);
        }

        System.assert(ctrl.cases.size() <= ctrl.listSize);
        
        System.assertEquals(1, ctrl.currentPage);
        System.assertEquals(0, ctrl.totalSize);
    }

}