force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region</description>
    <label>OU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Territory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>ROA</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FINS</fullName>
            </value>
            <value>
                <fullName>HLS</fullName>
            </value>
            <value>
                <fullName>RCG</fullName>
            </value>
            <value>
                <fullName>CMT</fullName>
            </value>
            <value>
                <fullName>EBU</fullName>
            </value>
            <value>
                <fullName>CBU</fullName>
            </value>
            <value>
                <fullName>PubSec</fullName>
            </value>
            <value>
                <fullName>DACH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Theater</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMER</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>DACH</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>SEEMA</fullName>
            </value>
            <value>
                <fullName>ASEAN</fullName>
            </value>
            <value>
                <fullName>NORTH APAC</fullName>
            </value>
            <value>
                <fullName>KOR</fullName>
            </value>
            <value>
                <fullName>INDIAN SUB</fullName>
            </value>
            <value>
                <fullName>JP</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Support.recordType-meta.xml
<RecordType>
    <fullName>Support</fullName>
    <active>true</active>
    <businessProcess>CS Tech Request</businessProcess>
    <label>Support</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/TRL.recordType-meta.xml
<RecordType>
    <fullName>TRL</fullName>
    <active>true</active>
    <businessProcess>CS Tech Request</businessProcess>
    <label>CS Tech Request</label>
</RecordType>

force-app/main/default/classes/TRL_ObjectPicklistUtilTest.cls
/**
 * TRL_ObjectPicklistUtilTest Test class support metadata services, picklist values,
 * in context of TRL for Case.Status and Account.Territory__c, Account.Region__c fields.
 * These tests rely on metdata of picklists
 * 
 * @author Igor Androsov
 * @version 1.0
 */
@IsTest
private class TRL_ObjectPicklistUtilTest {

    @IsTest
    static void testSelectOptionFromPicklist(){
        
        Test.startTest();
        // Case status
        List<TRL_ObjectPicklistUtil.PickList> statusList = TRL_ObjectPicklistUtil.getSelectOptionFromPicklist('Case', 'Status', true);

        Test.stopTest();
        System.assertEquals(true, statusList.size()>0);
        System.assertEquals('--None--', statusList[0].value);
    }

    @IsTest
    static void testTerritoryList(){
        
        Test.startTest();
        List<TRL_ObjectPicklistUtil.PickList> territoryList = TRL_ObjectPicklistUtil.getSelectOptionFromPicklist('Account', 'Territory__c', true);

        Test.stopTest();
        System.assertEquals(true, territoryList.size()>0);
        System.assertEquals('--None--', territoryList[0].value);
        for(TRL_ObjectPicklistUtil.PickList p : territoryList){
            // try to find values
            if(p.value=='APAC'){
                System.assertEquals('APAC', p.value); 
                System.assertEquals('APAC', p.label);
            }
        }
    }
    @IsTest
    static void testGetDependentOptions(){

        Test.startTest();
        Map<String,List<TRL_ObjectPicklistUtil.PickList>> mp = TRL_ObjectPicklistUtil.GetDependentOptionsEX('Account', 'Territory__c', 'Region__c');

        Test.stopTest();
        System.assertEquals(true, mp.size()>0);
        

    }

}