force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region</description>
    <label>OU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Territory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>ROA</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FINS</fullName>
            </value>
            <value>
                <fullName>HLS</fullName>
            </value>
            <value>
                <fullName>RCG</fullName>
            </value>
            <value>
                <fullName>CMT</fullName>
            </value>
            <value>
                <fullName>EBU</fullName>
            </value>
            <value>
                <fullName>CBU</fullName>
            </value>
            <value>
                <fullName>PubSec</fullName>
            </value>
            <value>
                <fullName>DACH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Theater</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMER</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>DACH</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>SEEMA</fullName>
            </value>
            <value>
                <fullName>ASEAN</fullName>
            </value>
            <value>
                <fullName>NORTH APAC</fullName>
            </value>
            <value>
                <fullName>KOR</fullName>
            </value>
            <value>
                <fullName>INDIAN SUB</fullName>
            </value>
            <value>
                <fullName>JP</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/TRL.recordType-meta.xml
<RecordType>
    <fullName>TRL</fullName>
    <active>true</active>
    <businessProcess>CS Tech Request</businessProcess>
    <label>CS Tech Request</label>
</RecordType>

force-app/main/default/classes/TRL_Action_New_CTRLTest.cls
@IsTest
public class TRL_Action_New_CTRLTest {
    
    @IsTest
    static void testTRL_Action_New_CTRL(){
        Test.startTest();
        
        TRL_Action_New_CTRL ctrl = new TRL_Action_New_CTRL();
        
        Test.stopTest();
        
        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');
        System.assertEquals(trlRecordType.getRecordTypeId(), ctrl.newCase.RecordTypeId);   
        
        AssignmentRule useAssignRule = [SELECT Id FROM AssignmentRule WHERE SobjectType = 'Case' AND Active = TRUE LIMIT 1];
        System.assertEquals(useAssignRule.Id, ctrl.newCase.getOptions().assignmentRuleHeader.assignmentRuleId);
    }
    
    @isTest static void testSave(){
        TRL_Action_New_CTRL ctrl = new TRL_Action_New_CTRL();
        ctrl.newCase.Subject = 'Test Save';
        ctrl.newCase.Description = 'Test Save Dscr';
        
        Test.startTest();
        
        ctrl.save();        
        
        Test.stopTest();
                   
        Case testCase = [SELECT Subject, Description FROM Case WHERE Id = :ctrl.newCase.Id LIMIT 1];
        System.assertEquals('Test Save', testCase.Subject);
        System.assertEquals('Test Save Dscr', testCase.Description);
    }
    
    @isTest static void testSaveError(){
        Account account1 = new Account(Name = 'TestAccount1', Territory__c = 'APAC', Region__c = 'Japan', BillingCountry = 'Japan');
        insert account1;
        TRL_Action_New_CTRL ctrl = new TRL_Action_New_CTRL();
        ctrl.newCase.Subject = 'Test Save';
        ctrl.newCase.Description = 'Test Save Dscr';
        ctrl.newCase.AccountId = account1.Id;
        insert ctrl.newCase;
        
        Test.startTest();
        
        ctrl.save();        
        
        Test.stopTest();
                   
		List<ApexPages.Message> pageMessages = ApexPages.getMessages();
        System.assertNotEquals(0, pageMessages.size());
        Boolean messageFound = false;
        for(ApexPages.Message message : pageMessages) {
            if( message.getDetail() == 'You can not create case' && message.getSeverity() == ApexPages.Severity.ERROR) {
                messageFound = true;
            }
        }
        System.assert(messageFound);
        
    }
    
    @isTest 
    static void testSaveAndNew(){
        Account account1 = new Account(Name = 'TestAccount1', Territory__c = 'APAC', Region__c = 'Japan', BillingCountry = 'Japan');
        insert account1;

        PageReference pageRef = Page.TRL_Action_New;
        Test.setCurrentPage(pageRef);
        TRL_Action_New_CTRL ctrl = new TRL_Action_New_CTRL();
        ctrl.newCase.Subject = 'Test Save';
        ctrl.newCase.Description = 'Test Save Dscr';
        ctrl.newCase.AccountId = account1.Id;

        Test.startTest();
        
        ctrl.saveAndNew();        
        
        Test.stopTest();
                   
        Case testCase = [SELECT Subject, Description FROM Case WHERE Id = :ctrl.newCase.Id LIMIT 1];
        System.assertEquals('Test Save', testCase.Subject);
        System.assertEquals('Test Save Dscr', testCase.Description);
    }
    
    @isTest 
    static void testSaveAndNewError(){
        PageReference pageRef = Page.TRL_Action_New;
        Test.setCurrentPage(pageRef);
        TRL_Action_New_CTRL ctrl = new TRL_Action_New_CTRL();
        ctrl.newCase.Subject = 'Test Save';
        ctrl.newCase.Description = 'Test Save Dscr';
        insert ctrl.newCase;
        
        Test.startTest();
        
        ctrl.saveAndNew();        
        
        Test.stopTest();
                   
		List<ApexPages.Message> pageMessages = ApexPages.getMessages();
        System.assertNotEquals(0, pageMessages.size());
        Boolean messageFound = false;
        for(ApexPages.Message message : pageMessages) {
            if( message.getDetail() == 'You can not create case' && message.getSeverity() == ApexPages.Severity.ERROR) {
                messageFound = true;
            }
        }
        System.assert(messageFound);
        
    }
    
    @IsTest
    static void testCancel(){
        TRL_Action_New_CTRL ctrl = new TRL_Action_New_CTRL();
        
        Test.startTest();
        
        PageReference testRef = ctrl.cancel();        
        
        Test.stopTest();
        
        System.assertNotEquals(null, testRef);
        System.assert(testRef.getRedirect());
    }

}