force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region</description>
    <label>OU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Territory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>ROA</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FINS</fullName>
            </value>
            <value>
                <fullName>HLS</fullName>
            </value>
            <value>
                <fullName>RCG</fullName>
            </value>
            <value>
                <fullName>CMT</fullName>
            </value>
            <value>
                <fullName>EBU</fullName>
            </value>
            <value>
                <fullName>CBU</fullName>
            </value>
            <value>
                <fullName>PubSec</fullName>
            </value>
            <value>
                <fullName>DACH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Theater</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMER</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>ROW</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Account_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Region__c</fullName>
    <formula>TEXT(Account.Territory__c) + &quot; - &quot; + TEXT(Account.Region__c)</formula>
    <label>Account Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CS_Activity__c.field-meta.xml
<CustomField>
    <fullName>CS_Activity__c</fullName>
    <description>Defines a list of CS Activities and Plays</description>
    <inlineHelpText>Defines a list of CS Activities and Plays</inlineHelpText>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CS_Reason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Anypoint Community Manager</fullName>
            </value>
            <value>
                <fullName>Anypoint Partner Manager</fullName>
            </value>
            <value>
                <fullName>API Designer API Manager</fullName>
            </value>
            <value>
                <fullName>API LC - Async</fullName>
            </value>
            <value>
                <fullName>API Lifecycle - CICD</fullName>
            </value>
            <value>
                <fullName>API Monetization</fullName>
            </value>
            <value>
                <fullName>Architecture Roadmapping</fullName>
            </value>
            <value>
                <fullName>Architecture Review</fullName>
            </value>
            <value>
                <fullName>BrownBags</fullName>
            </value>
            <value>
                <fullName>CaMA</fullName>
            </value>
            <value>
                <fullName>Citizen</fullName>
            </value>
            <value>
                <fullName>Composability Workshop</fullName>
            </value>
            <value>
                <fullName>C4E Workshop</fullName>
            </value>
            <value>
                <fullName>Dashboard and Metrics</fullName>
            </value>
            <value>
                <fullName>Deployment - Cloud</fullName>
            </value>
            <value>
                <fullName>Deployment - GovCloud</fullName>
            </value>
            <value>
                <fullName>Deployment - Hybrid</fullName>
            </value>
            <value>
                <fullName>Deployment - Onprem</fullName>
            </value>
            <value>
                <fullName>Enterprise Connectivity - Connectors</fullName>
            </value>
            <value>
                <fullName>Enterprise Connectivity - ERP</fullName>
            </value>
            <value>
                <fullName>Enterprise Connectivity - Salesforce</fullName>
            </value>
            <value>
                <fullName>Exchange</fullName>
            </value>
            <value>
                <fullName>General architectural advice</fullName>
            </value>
            <value>
                <fullName>General Design advice</fullName>
            </value>
            <value>
                <fullName>General Product advice</fullName>
            </value>
            <value>
                <fullName>Go-Live Readiness</fullName>
            </value>
            <value>
                <fullName>GraphQL(API Federation)</fullName>
            </value>
            <value>
                <fullName>Hackathon</fullName>
            </value>
            <value>
                <fullName>Health Check</fullName>
            </value>
            <value>
                <fullName>KPI Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CS_Reason__c.field-meta.xml
<CustomField>
    <fullName>CS_Reason__c</fullName>
    <description>CS reason for Tech Request</description>
    <inlineHelpText>CS reason for Tech Request</inlineHelpText>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success Planning and Advisory</fullName>
            </value>
            <value>
                <fullName>Product Specialization</fullName>
            </value>
            <value>
                <fullName>CSSA Strategic Plays</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CSA_CSE__c.field-meta.xml
<CustomField>
    <fullName>CSA_CSE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSA/CSE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Level_of_Priority__c.field-meta.xml
<CustomField>
    <fullName>Level_of_Priority__c</fullName>
    <label>Level of Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>DACH</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>SEEMA</fullName>
            </value>
            <value>
                <fullName>ASEAN</fullName>
            </value>
            <value>
                <fullName>NORTH APAC</fullName>
            </value>
            <value>
                <fullName>KOR</fullName>
            </value>
            <value>
                <fullName>INDIAN SUB</fullName>
            </value>
            <value>
                <fullName>JP</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/TRL_Type__c.field-meta.xml
<CustomField>
    <fullName>TRL_Type__c</fullName>
    <description>CS Request Type classify requests as INTERNAL or Others</description>
    <inlineHelpText>CS Request Type classify requests as INTERNAL or Others</inlineHelpText>
    <label>CS Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INTERNAL</fullName>
                <default>true</default>
                <label>Internal</label>
            </value>
            <value>
                <fullName>ADHOC</fullName>
                <label>Ad-Hoc</label>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/TRL.recordType-meta.xml
<RecordType>
    <fullName>TRL</fullName>
    <active>true</active>
    <businessProcess>CS Tech Request</businessProcess>
    <label>CS Tech Request</label>
</RecordType>

force-app/main/default/objects/User/fields/TRLcases__c.field-meta.xml
<CustomField>
    <fullName>TRLcases__c</fullName>
    <label>TRL cases user type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requestor</fullName>
                <default>true</default>
                <label>Requestor</label>
            </value>
            <value>
                <fullName>CS Tech Lead</fullName>
            </value>
            <value>
                <fullName>AssignedTo Person</fullName>
            </value>
            <value>
                <fullName>Super User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TRL_Action_Edit_CTRLTest.cls
@IsTest
public class TRL_Action_Edit_CTRLTest {
    
    @testSetUp
    static void setUpData(){
        Account account1 = new Account(Name = 'TestAccount1', Territory__c = 'APAC', Region__c = 'Japan', BillingCountry = 'Japan');
        insert account1;
        
        Schema.RecordTypeInfo trlRecordType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('TRL');
        Case testCase = new Case();
        testCase.RecordTypeId = trlRecordType.getRecordTypeId();
        testCase.Subject = 'TRL Case subject';
        testCase.AccountId = account1.Id;
        insert testCase;
    }
    
    @IsTest 
    static void testUpdateRecord(){
        Case testCase = [SELECT Id, AccountId, Account.Name, Subject, CaseNumber, Status, Type, CreatedById,
                            CreatedDate, Account_Region__c, Level_of_Priority__c, CSA_CSE__c, TRL_Type__c, 
                            CS_Reason__c, CS_Activity__c
                            FROM Case WHERE Subject = 'TRL Case subject' LIMIT 1];
        testCase.Subject = 'Test Case';
        ApexPages.StandardController caseStdCtrl = new ApexPages.StandardController(testCase);
        TRL_Action_Edit_CTRL ctrl = new TRL_Action_Edit_CTRL(caseStdCtrl);

        User currentUser = new User(Id = UserInfo.getUserId(), TRLcases__c = 'Super User');
        update currentUser;
        
        Test.startTest();
        
        ctrl.updateRecord();
        
        Test.stopTest();
        
        Case resultCase = [SELECT Subject FROM Case WHERE Id = :testCase.Id LIMIT 1];
        System.assertEquals('Test Case', resultCase.Subject);
    }
    
    @IsTest 
    static void testUpdateRecordError(){
        ApexPages.StandardController caseStdCtrl = new ApexPages.StandardController(new Case());
        TRL_Action_Edit_CTRL ctrl = new TRL_Action_Edit_CTRL(caseStdCtrl);
        
        Test.startTest();
        
        ctrl.updateRecord();
        
        Test.stopTest();
        
		List<ApexPages.Message> pageMessages = ApexPages.getMessages();
        System.assertNotEquals(0, pageMessages.size());
        Boolean messageFound = false;
        for(ApexPages.Message message : pageMessages) {
            if( message.getDetail() == 'You can not edit the case' && message.getSeverity() == ApexPages.Severity.ERROR) {
                messageFound = true;
            }
        }
        System.assert(messageFound);
        
    }
    
    @IsTest 
    static void testSaveAndNew(){
        Case testCase = [SELECT Id, AccountId, Account.Name, Subject, CaseNumber, Status, Type, CreatedById,
                                CreatedDate, Account_Region__c, Level_of_Priority__c, CSA_CSE__c, TRL_Type__c, 
                                CS_Reason__c, CS_Activity__c
                                FROM Case WHERE Subject = 'TRL Case subject' LIMIT 1];
        testCase.Subject = 'Test Case';
        ApexPages.StandardController caseStdCtrl = new ApexPages.StandardController(testCase);
        TRL_Action_Edit_CTRL ctrl = new TRL_Action_Edit_CTRL(caseStdCtrl);

        User currentUser = new User(Id = UserInfo.getUserId(), TRLcases__c = 'Super User');
        update currentUser;

        Test.startTest();
        
        ctrl.saveAndNew();
        
        Test.stopTest();
        
        Case resultCase = [SELECT Subject FROM Case WHERE Id = :testCase.Id LIMIT 1];
        System.assertEquals('Test Case', resultCase.Subject);
    }
    
    @IsTest 
    static void testSaveAndNewError(){
        ApexPages.StandardController caseStdCtrl = new ApexPages.StandardController(new Case());
        TRL_Action_Edit_CTRL ctrl = new TRL_Action_Edit_CTRL(caseStdCtrl);
        
        Test.startTest();
        
        ctrl.saveAndNew();
        
        Test.stopTest();
        
		List<ApexPages.Message> pageMessages = ApexPages.getMessages();
        System.assertNotEquals(0, pageMessages.size());
        Boolean messageFound = false;
        for(ApexPages.Message message : pageMessages) {
            if( message.getDetail() == 'You can not edit the case' && message.getSeverity() == ApexPages.Severity.ERROR) {
                messageFound = true;
            }
        }
        System.assert(messageFound);
        
    }
    
    @IsTest
    static void testCancel(){
        ApexPages.StandardController caseStdCtrl = new ApexPages.StandardController(new Case());
        TRL_Action_Edit_CTRL ctrl = new TRL_Action_Edit_CTRL(caseStdCtrl);
        
        Test.startTest();
        
        PageReference testRef = ctrl.cancel();        
        
        Test.stopTest();
        
        System.assertNotEquals(null, testRef);
        System.assert(testRef.getRedirect());
    }

}