force-app/main/default/objects/TRL_Case_Priorization_Event__e/TRL_Case_Priorization_Event__e.object-meta.xml
<CustomObject>
    <description>#W-8097697 TRL Priorization thoeger@mulesoft.com</description>
    <label>TRL_Case_Priorization_Event</label>
    <pluralLabel>TRL_Case_Priorization_Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/TRL_Case_Priorization_Event__e/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>Case.AccountId</description>
    <label>AccountId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TRL_Case_Priorization_Event__e/fields/CaseID__c.field-meta.xml
<CustomField>
    <fullName>CaseID__c</fullName>
    <label>CaseID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TRL_Submit_CasePlatformEvent.cls
/***
*  @name: TRL_Submit_CasePlatformEvent to externalize method for submission of the PE
*  @GUS: #W-8097697
*  @Author: thoeger@mulesoft.com
*  @CreationDate: 2020-October-21
* 
* */
public class TRL_Submit_CasePlatformEvent {
    
    Final string DebugClass = '## TRL_Submit_CasePlatformEvent ';
    
    public void Submit_TRL_CasePlatformEvent(Case c)
    {
        List<case> CaseLst = new List<case>();
        CaseLst.add(c);
        Submit_TRL_CasePlatformEvent(CaseLst);
    }
    
    
    public void Submit_TRL_CasePlatformEvent(List<case> CaseLst)
    {
        Final String DebugMethod = DebugClass + '## Submit_TRL_CasePlatformEvent ';
        List<TRL_Case_Priorization_Event__e> CPELst = new List<TRL_Case_Priorization_Event__e>();
        
        for (Case c : CaseLst)
        {
            TRL_Case_Priorization_Event__e newEvent = new TRL_Case_Priorization_Event__e(
                AccountId__c=c.AccountID,
                CaseID__c=c.id
            );
            CPELst.add(newEvent);
        }
        // Call method to publish events
        system.debug(DebugClass + ' newEvents:'+CPELst);
        List<Database.SaveResult> srlst = EventBus.publish(CPELst);
        system.debug(DebugClass + ' PublishEventResults:'+srlst);
        // Inspect publishing result
        for (Database.SaveResult sr   : srlst)
        {
            if (sr.isSuccess()) {
                System.debug( DebugClass +  'Successfully published event.');
            } else {
                for(Database.Error err : sr.getErrors()) {
                    System.debug( DebugClass + 'Error returned: ' +
                                 err.getStatusCode() +
                                 ' - ' +
                                 err.getMessage());
                }
            }
        }
        
        
    }
}